apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-kubernetes
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "http://k8s-dev.eastus.cloudapp.azure.com/"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: hello-kubernetes
              port:
                number: 80