apiVersion: argoproj.io/v1alpha1
kind: "Application"
metadata: 
  name: "postgres-data-generator"
  namespace: "cicd"
spec: 
  project: "big-data-on-k8s"
  source: 
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: "11.0.8"
    chart: "postgresql"
    helm: 
      version: "v3"
      parameters:
        - name: auth.postgresPassword
          value: "adminpassword"
        - name: auth.database
          value: "ifood"
        - name: auth.username
          value: "ifood_app"
        - name: auth.password
          value: "ifood123"
        - name: auth.replicationUsername
          value: "repl_user"
        - name: auth.replicationPassword
          value: "repl_user123"
        - name: primary.extendedConfiguration
          value: |-
            wal_level=logical
            max_wal_senders=1
            max_replication_slots=1
        # - name: primary.pgHbaConfiguration
        #   value: |-
        #     local replication all trust
        #     host replication all localhost trust
        #     host replication all ::1/128 trust
      releaseName: my-postgresql
  destination: 
    server: "https://kubernetes.default.svc"
    namespace: "data-generator"
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
    retry: 
      limit: 3
      backoff: 
        duration   : "5s"
        factor     : 2
        maxDuration: "1m"