---
## You can override the default chart name (i.e., .Charts.name) when desired using the following parameter.
## This is the only way to have more than one deployment of this
nameOverride: null

## Number of Hive Metastore instances.
## Following the documentation, given Hive Metastore is stateless we could have more than one instance.
## https://cwiki.apache.org/confluence/display/Hive/AdminManual+Metastore+Administration
replicaCount: 1

## Default Hive image and tag. Please build image locally before applying this.
image:
  name: jpedroloureiro/hive-metastore
  tag: 1.0.0
  pullPolicy: Always


env:
  HIVE_DB_EXTERNAL: "false"
  HIVE_DB_NAME: metastore_db
  FS_S3A_ACCESS_KEY: T11ZDXNGN4MCJF2PZ393
  FS_S3A_SECRET_KEY: gvrgSv49v4ZPgBqnOPQFh3iR7rxti+iEC8WOWM10
  FS_S3A_ENDPOINT: "http://minio.datalake.svc.cluster.local:9000"
  FS_S3A_PATH_STYLE_ACCESS: "true"


## Resource requests and limits: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 1
    memory: 250m

service:
  type: ClusterIP
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
      protocol: TCP

## Auto-scaling (hpa) configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90