apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalake-tables-generator
spec:
  selector:
    matchLabels:
      name: datalake-tables-generator
  template:
    metadata:
      labels:
        name: datalake-tables-generator
    spec:
      containers:
        - name: datalake-tables-generator
          image: jpedroloureiro/datalake_tables_generator:0.0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 100Mi
              cpu: 150m
            limits:
              memory: 100Mi
              cpu: 150m