apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  labels:
    app: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:5.5.1
        ports:
        - containerPort: 8081
        imagePullPolicy: Always
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "200m"
        # env:
        # - name: SCHEMA_REGISTRY_HOST_NAME
        #   value: schema-registry
        # - name: SCHEMA_REGISTRY_LISTENERS
        #   value: http://0.0.0.0:8081
        # - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
        #   value: kafka-cluster-zookeeper-client:2181
        # command:
        # - bash
        # - -c
        # - unset SCHEMA_REGISTRY_PORT; /etc/confluent/docker/run
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: PLAINTEXT://kafka-cluster-kafka-brokers:9092
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
          value: PLAINTEXT
        command:
        - bash
        - -c
        - unset SCHEMA_REGISTRY_PORT; /etc/confluent/docker/run


# containers:
#       - name: my-cluster-schema-registry
#         image: confluentinc/cp-schema-registry:4.1.1-2
#         ports:
#         - containerPort: 8081
#         env:
#         - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
#           value: PLAINTEXT://my-cluster-kafka:9092
#         - name: SCHEMA_REGISTRY_HOST_NAME
#           valueFrom:
#             fieldRef:
#               fieldPath: status.podIP
#         - name: SCHEMA_REGISTRY_LISTENERS
#           value: http://0.0.0.0:8081
#         - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
#           value: PLAINTEXT