apiVersion: argoproj.io/v1alpha1
kind: "Application"
metadata: 
  name: "postgres-data-generator"
  namespace: "cicd"
spec: 
  project: "big-data-on-k8s"
  source: 
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: "10.16.2"
    chart: "postgresql"
    helm: 
      version: "v3"
      parameters:
        - name: global.postgresql.postgresqlDatabase
          value: "ifood"
        - name: global.postgresql.postgresqlUsername
          value: "ifood_app"
        - name: global.postgresql.postgresqlPassword
          value: "ifood123"
      releaseName: my-postgresql
  destination: 
    server: "https://kubernetes.default.svc"
    namespace: "data-generator"
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
    retry: 
      limit: 3
      backoff: 
        duration   : "5s"
        factor     : 2
        maxDuration: "1m"