apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: apache-airflow-remote
  namespace: cicd
spec:
  project: big-data-on-k8s
  source:
    repoURL: https://airflow.apache.org/
    targetRevision: 1.6.0
    chart: airflow
    helm:
      version: v3
      values: |
        createUserJob:
          useHelmHooks: false
        migrateDatabaseJob:
          useHelmHooks: false
        workers:
          replicas: 1
          persistence:
            size: 50Gi
          resources: 
            limits:
              cpu: 1000m
              memory: 3Gi
            requests:
              cpu: 500m
              memory: 2Gi
        scheduler:
          replicas: 1
          resources: 
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 1Gi
        webserver:
          replicas: 1
          resources:
            limits:
              cpu: 2000m
              memory: 3Gi
            requests:
              cpu: 1500m
              memory: 3Gi
          defaultUser:
            password: bigdataonk8s
        dags:
          gitSync:
            enabled: true
            repo: https://github.com/JPedro-loureiro/big_data_k8s.git
            branch: main
            depth: 0
            subPath: "apps/orchestration/airflow/dags"
            wait: 30
        ingress:
          enabled: true
          web:
            annotations:
              kubernetes.io/ingress.class: "nginx"
              nginx.ingress.kubernetes.io/rewrite-target: "/"
              cert-manager.io/cluster-issuer: "lets-encrypt-cluster-issuer"
            path: "/"
            hosts: [
              airflow.qa.bigdataonk8s.com,
            ]
            tls:
              enabled: true
              secretName: "airflow-tls-secret"
  destination:
    server: https://kubernetes.default.svc
    namespace: orchestration-remote
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
    retry:
      limit: 3
      backoff:
        duration   : "5s"
        factor     : 2
        maxDuration: "1m"