apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: spark-operator
  namespace: cicd
spec:
  project: big-data-on-k8s
  source:
    repoURL: https://googlecloudplatform.github.io/spark-on-k8s-operator
    targetRevision: v1beta2-1.3.3-3.1.1
    chart: spark-operator
    helm:
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: processing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
    retry:
      limit: 3
      backoff:
        duration   : "5s"
        factor     : 2
        maxDuration: "1m"
